/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quinela;

import javax.swing.JOptionPane;
import java.util.Arrays;

/**
 *
 * @author sebastianqr.2208
 */
public class Quinela extends javax.swing.JFrame {
    int estado_password = 0;
    private String usuario_global;
    ManejadorArchivos manejadorArchivos = new ManejadorArchivos();
    /**
     * Creates new form Quinela
     */
    public Quinela() {
        initComponents();
        //panel_multiple.setSelectedIndex(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantallas = new javax.swing.JTabbedPane();
        login = new javax.swing.JPanel();
        iniciar_label = new javax.swing.JLabel();
        username_field_login = new javax.swing.JTextField();
        username_label_login = new javax.swing.JLabel();
        password_label_login = new javax.swing.JLabel();
        acceder_button_login = new javax.swing.JButton();
        registrarse_button_login = new javax.swing.JButton();
        password_field_login = new javax.swing.JPasswordField();
        mostrar_button_login = new javax.swing.JRadioButton();
        registrar = new javax.swing.JPanel();
        registrarse_label_registrarse = new javax.swing.JLabel();
        username_field_registrarse = new javax.swing.JTextField();
        username_label_registrarse = new javax.swing.JLabel();
        password_field_registrarse = new javax.swing.JTextField();
        password_label_registrarse = new javax.swing.JLabel();
        registrar_button_registrarse = new javax.swing.JButton();
        login_button_registrarse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iniciar_label.setFont(new java.awt.Font("Avenir", 1, 24)); // NOI18N
        iniciar_label.setText("Iniciar Sesión");

        username_field_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_field_loginActionPerformed(evt);
            }
        });

        username_label_login.setText("Username");

        password_label_login.setText("Password");

        acceder_button_login.setText("Acceder");
        acceder_button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceder_button_loginActionPerformed(evt);
            }
        });

        registrarse_button_login.setText("Registrarse");
        registrarse_button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarse_button_loginActionPerformed(evt);
            }
        });

        mostrar_button_login.setText("Mostrar Contraseña");
        mostrar_button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrar_button_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(459, 459, 459)
                .addComponent(acceder_button_login, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(username_field_login, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(iniciar_label))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(password_field_login, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(225, 225, 225))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(username_label_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 536, Short.MAX_VALUE)
                .addComponent(password_label_login)
                .addGap(316, 316, 316))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                        .addComponent(registrarse_button_login)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                        .addComponent(mostrar_button_login)
                        .addGap(278, 278, 278))))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(iniciar_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_field_login, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_field_login, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_label_login)
                    .addComponent(password_label_login))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mostrar_button_login)
                .addGap(74, 74, 74)
                .addComponent(acceder_button_login, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                .addComponent(registrarse_button_login)
                .addGap(15, 15, 15))
        );

        pantallas.addTab("tab1", login);

        registrarse_label_registrarse.setFont(new java.awt.Font("Avenir", 1, 24)); // NOI18N
        registrarse_label_registrarse.setText("Registrarse");

        username_label_registrarse.setText("Username");

        password_label_registrarse.setText("Password");

        registrar_button_registrarse.setText("Registrar");
        registrar_button_registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_button_registrarseActionPerformed(evt);
            }
        });

        login_button_registrarse.setText("Login");
        login_button_registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_button_registrarseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registrarLayout = new javax.swing.GroupLayout(registrar);
        registrar.setLayout(registrarLayout);
        registrarLayout.setHorizontalGroup(
            registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(username_field_registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                .addComponent(password_field_registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
            .addGroup(registrarLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(username_label_registrarse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(password_label_registrarse)
                .addGap(281, 281, 281))
            .addGroup(registrarLayout.createSequentialGroup()
                .addGroup(registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrarLayout.createSequentialGroup()
                        .addGap(520, 520, 520)
                        .addComponent(registrarse_label_registrarse))
                    .addGroup(registrarLayout.createSequentialGroup()
                        .addGap(457, 457, 457)
                        .addComponent(registrar_button_registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login_button_registrarse)
                .addGap(14, 14, 14))
        );
        registrarLayout.setVerticalGroup(
            registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(registrarse_label_registrarse)
                .addGap(113, 113, 113)
                .addGroup(registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_field_registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_field_registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_label_registrarse)
                    .addComponent(password_label_registrarse))
                .addGap(90, 90, 90)
                .addComponent(registrar_button_registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addComponent(login_button_registrarse)
                .addContainerGap())
        );

        pantallas.addTab("tab2", registrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantallas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantallas))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    private void escribir(String ruta, String data){
        String info = manejadorArchivos.leer(ruta);
        int escribir = manejadorArchivos.escribir(ruta, info + data);

        if(escribir == 1){
            JOptionPane.showMessageDialog(pantallas, "Ocurrio un error, intente de nuevo!!!!");
        }
    }

    private Boolean encontrar_usuario(String username, String password){
        String todos = manejadorArchivos.leer("archivos/usuarios.txt");
        String[] usuarios = todos.split("#");
        String[] datos;

        for(String usuario : usuarios){
            if(!usuario.equals("")){
                datos = usuario.split("-");
                if(datos[0].equals(username) && datos[1].equals(password)){
                    return true;
                }
            }
        }
        return false;
    }

    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    private void registrarse_button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarse_button_loginActionPerformed
        pantallas.setSelectedIndex(1);
    }//GEN-LAST:event_registrarse_button_loginActionPerformed

    private void acceder_button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceder_button_loginActionPerformed
        // TODO add your handling code here:
        String username = username_field_login.getText();
        String password = String.valueOf(password_field_login.getPassword());

        if(!username.equals("") && !password.equals("")){
            if(encontrar_usuario(username, password)){
                usuario_global = username;
                System.out.println("Se encuentra el usuario");
            }
            else{
                JOptionPane.showMessageDialog(pantallas, "No se encontro a este usuario!!!","ERROR!", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(pantallas, "Debe escribir un Usuario y una Constraseña!!!","ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_acceder_button_loginActionPerformed

    private void username_field_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_field_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_field_loginActionPerformed

    private void registrar_button_registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_button_registrarseActionPerformed
        // TODO add your handling code here:
        String username = username_field_registrarse.getText();
        String password = password_field_registrarse.getText();
        if(!username.equals("") && !password.equals("")){
            int opcion = JOptionPane.showConfirmDialog(pantallas, "Desea agregar al usuario -" + username + "- al sistema?");
            switch (opcion){
                case JOptionPane.YES_OPTION:
                    escribir("archivos/usuarios.txt", "#" + username + "-" + password);
                    JOptionPane.showMessageDialog(pantallas,"Se agregó a -" + username + "- al sistema!");
                    username_field_login.setText(username);
                    password_field_login.setText(password);
                    pantallas.setSelectedIndex(0);
                    username_field_registrarse.setText("");
                    password_field_registrarse.setText("");

                case JOptionPane.NO_OPTION:
                    break;
            }
        }
        else{
            JOptionPane.showMessageDialog(pantallas, "Debe escribir un Usuario y una Constraseña!!!","ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registrar_button_registrarseActionPerformed

    private void login_button_registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_button_registrarseActionPerformed
        // TODO add your handling code here:
        pantallas.setSelectedIndex(0);
    }//GEN-LAST:event_login_button_registrarseActionPerformed

    private void mostrar_button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrar_button_loginActionPerformed
        // TODO add your handling code here:
        if(estado_password == 0){
            password_field_login.setEchoChar((char)0);
            estado_password = 1;
        }else{
            password_field_login.setEchoChar('*');
            estado_password = 0;
        }
    }//GEN-LAST:event_mostrar_button_loginActionPerformed

    private void Font(javax.swing.JLabel label){
        label.setFont(new java.awt.Font("Avenir", 1, 24));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quinela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quinela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quinela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quinela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quinela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton acceder_button_login;
    private javax.swing.JLabel iniciar_label;
    public javax.swing.JPanel login;
    public javax.swing.JButton login_button_registrarse;
    public javax.swing.JRadioButton mostrar_button_login;
    public javax.swing.JTabbedPane pantallas;
    public javax.swing.JPasswordField password_field_login;
    public javax.swing.JTextField password_field_registrarse;
    public javax.swing.JLabel password_label_login;
    public javax.swing.JLabel password_label_registrarse;
    private javax.swing.JPanel registrar;
    public javax.swing.JButton registrar_button_registrarse;
    public javax.swing.JButton registrarse_button_login;
    public javax.swing.JLabel registrarse_label_registrarse;
    public javax.swing.JTextField username_field_login;
    public javax.swing.JTextField username_field_registrarse;
    public javax.swing.JLabel username_label_login;
    public javax.swing.JLabel username_label_registrarse;
    // End of variables declaration//GEN-END:variables
}
